spring:
  datasource:
    url: jdbc:mysql://localhost:3306/persons?useTimezone=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show_sql: false
springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
